### PR TITLE
added settings, support for settings in inject.js, also contains my attribution change

### PR DESCRIPTION
**Pull request by Ethicmeta**
Added settings.js and usersettings.html. The frontend needs to be prettified and is just a place holder. 

inject.js now handles whether or not user wants to attribute, and if they want to attribute it'll also read the commenting field for commenting syntax. 

change line 14 of settings.js for a message to display shortly after settings have been saved.

### CODE REVIEW

**Comment by studenton** [comment]
Thanks.

Can you make me clear on the **it'll also read the commenting field for commenting syntax*? I didn't understand its purpose.

**Comment by kot91** [comment]
@studenton sure, the commenting input field on the usersettings.html takes whatever the user submits as the "commenting style". E.G. user clicks the attribution check box, types in the commenting style (// or `, for example) and it applies it after <br/><br/> before the 'source: link'. If attribution is not checked it won't apply what the user inputs as commenting style.

This allows for us to handle ANY commenting syntax that does not require a closer ( for example, wouldn't work. same for /* */ though this is the // multiline syntax)

**Comment by studenton** [comment]
Commenting style depends on the programming language. So will taking user input for the comment style cover all the cases? The user might want to copy a Ruby code where // doesn't work for commenting.

**Comment by kot91** [comment]
@studenton the user would update their settings to match the commenting style they intend on using.

The alternative suggestion of basing it on the tags is not as reliable as 1) Multiple tags for different languages, 2) incorrect tags or tags not covering the language discussed, and 3) expanding the extension to multiple or user defined websites would break attribution entirely.

**Comment by studenton** [comment]
If user has to update the comment style, won't it be easier for them to manually write the comment. 

If they do it manually:
1. Copy the page link
2. Write their comment style
3. Paste

If they do it through extension:
1. Goto extension settings
2. Update the comment section
3. Save
4. Reload the page
5. Copy the code
6. Paste

I don't think the effort is worth it. 

If you agree, let's drop this feature. Please update the PR and only include the implementation for settings page + your other edits. I'll merge it.

**Comment by kot91** [comment]
@studenton By default the attribution is off and commenting is blank. If the user wishes, they can turn on attribution without commenting (which I would recommend to a user if they are actively changing to different languages that frequently). 

It's a matter of preference at this point, the feature is flexible and I don't think it needs to be removed as it is not default, nor is it mandatory to have both attribution and commenting.

**Comment by studenton** [comment]
You got a point. Let's keep it completely optional. It caters to a set of people who work on a fixed language.

It'll be better to list such features under "Experimental" section in the settings page.

I'll review the code soon and merge this. Thanks for contributing :smile:

**Comment by studenton** [comment]
@kot91 I pulled your branch locally and tried out. There are few errors:
1. The folder should be **settings** but its named Settings. So I got an error while loading the extension.

2. The location to `scripts/settings/settings.js` is not present. You've the file at `settings/settings.js`.

**Comment by studenton** [comment]
@kot91 Btw, can you please check this PR to a different branch. Name it `dev` and send a PR to dev branch to this original repo. 

Since it's a `Work in Progress`, let's keep it in dev right now.

**Comment by studenton** [comment]
@kot91 Any updates on this? If you're stuck somewhere, feel free to share here. We can help you.

**Comment by kot91** [comment]
@studenton Hey, I'll have an update pushed shortly. I ran into an issue with browser detection (chrome vs. firefox). The doubleclick was not working because of this detection, but I've found a methodology to fix the problem. I have also fixed the manifest issue pointing to the incorrect settings page.

Also, this update will have settings restored per session. ie if you set the color, it'll populate in the settings menu by default (in this example border color defaults to #0D0. When you click options, #0D0 will be filled in on the input section for border highlight color).

Stay tuned!

**Comment by kot91** [comment]
my fix for browser detection did not pan out. Would it be a good idea to implement separate build folders for each browser?

**Pull request closed without merging**
