### PR TITLE
Starting work on the hotkeys

### PR DESCRIPTION
**Pull request by willbiddy**
#20

### CODE REVIEW

**Review by Ethicmeta — CHANGES_REQUESTED** [review]
See notes below

**Comment by amitness** [comment]
@willbiddy @kot91 Sorry, I'd been away for a while. Is this in progress?

**Comment by kot91** [comment]
@willbiddy @amitness Not sure. I tagged him with my suggested fix.

**Comment by willbiddy** [comment]
I was having some difficulty with it. if one of you want to work on it that would be good.

**Comment by amitness** [comment]
@willbiddy Sure. Can you tell us at what point you got stuck?

**Comment by willbiddy** [comment]
I added some buttons and was having difficulty getting them to work properly. @kot91 offered a fix, but it wasn't working for me.

**Comment by kot91** [comment]
@willbiddy @amitness I recommend taking the functionality you've worked on and adapting it to the current master build as the usersettings page has changed dramatically.

the current list of things to add to the current source dev branch is attribution option/commenting style as well as the hotkey functionality. Amitness, when you finish reviewing the remaining PRs let us know so we can be on the same working build.

**Comment by amitness** [comment]
@kot91 I've finished reviewing all.

**Pull request closed without merging**
